author: "Alexey Karapetov <karapetov@gmail.com>"
description: "A CLI tool to set/bump the `version` key in pubspec.yaml. Think of `npm version` for Dart."
homepage: "https://github.com/f3ath/pubspec-version"
name: "pubspec_version"
version: "0.0.2"
dependencies: 
  args: "^1.5.0"
  pub_semver: "^1.4.2"
  pubspec: "^0.1.0"
dev_dependencies: 
  mockito: "^3.0.0"
  test: "^1.0.0"
environment: 
  sdk: ">=2.0.0 <3.0.0"
executables: 
  pubspec-version: "pubspec-version"
